import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import './globals.css'
import { Inter } from 'next/font/google'
// import { ParticlesBackground } from '@/client/ParticlesBackground'
import { DarkMode } from '@/client/DarkMode'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: "Mohamed's Portfolio",
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <DarkMode />
        <Navbar className="vw-100" />
        {children}
        <Footer />
      </body>
    </html>
  );
}
