import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import './globals.css'
import { Inter } from 'next/font/google'
import { ParticlesBackground } from '@/client/ParticlesBackground'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: "Mohamed's Portfolio",
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar className="vw-100" />
        <ParticlesBackground />
        {children}
        <Footer />
      </body>
    </html>
  );
}
